### ISSUE TITLE
Installation von Latex (MikTex / TexStudio) unter MacOS

### ISSUE THREAD

**Issue by fleitnerfischerDHBW** [tkibler/vorlage_latex_doku#3]
**MikTex / Latex Distribution unter MacOS**
Unter MacOS kann es vor allem auf neueren Macs mit M-Prozessoren zu Problemen bei der Installation von MikTex kommen, da MikTex aktuell nur für X86-basierte Prozessoren verfügbar ist. 

Wenn man einen Mac benutzen möchte empfehle ich die MacTeX Latex Distribution welche Sie hier finden: 
[https://www.tug.org/mactex/](https://www.tug.org/mactex/)

Diese kann sowohl auf alten Intel Macs als auch auf den neuen Arm basierten Macs installiert werden. 

**TexStudio unter MacOS**
Da TexStudio nicht von Apple verifiziert werden kann bzw. die Entwickler keinen Apple Developer Account haben, wird die Ausführung von TexStudio blockiert. Sie können aber in den Einstellungen unter Datenschutz & Sicherheit im Bereich Sicherheit mit "Dennoch öffnen" das öffnen von TexStudio erzwingen. 

<img width="807" alt="TexStudio" src="https://github.com/tkibler/vorlage_latex_doku/assets/99406160/d1c06834-c292-4c2c-8ac9-7609cf560ae1">

**Comment by tkibler** [comment]
Danke für den Hinweis, welcher ins Wiki aufgenommen wurde.
